export const topMenuMasterTab = [
  {
    title: "User",
    number: 0,
    icon: "mdi-account-circle-outline",
    link: "/masters/users",
    link2: "/masters/users/create",
    permissions: ["r_users"],
  },
  {
    title: "Company Profile",
    number: 1,
    icon: "mdi-domain",
    link: "/masters/company-profiles",
    permissions: ["r_roles"],
  },
  {
    title: "Customer Type",
    number: 2,
    icon: "mdi-layers-outline",
    link: "/masters/customer-types",
    link2: "/masters/customer-types/create",
    permissions: ["r_ms"],
  },
  {
    title: "Customer",
    number: 3,
    icon: "mdi-book-account-outline",
    link: "/masters/customers",
    link2: "/masters/customers/create",
    permissions: ["r_ms"],
  },
  {
    title: "Item",
    number: 4,
    icon: "mdi-treasure-chest-outline",
    link: "/masters/items",
    link2: "/masters/items/create-item",
    permissions: ["r_items"],
  },
  {
    title: "Unit",
    number: 5,
    icon: "mdi-bookshelf",
    link: "/masters/units",
    link2: "/masters/units/create",
    permissions: ["r_ms"],
  },
  {
    title: "Warehouse",
    number: 6,
    icon: "mdi-warehouse",
    link: "/masters/warehouses",
    link2: "/masters/warehouses/create-warehouse",
    permissions: ["r_ms"],
  },
  {
    title: "Role & Permission",
    number: 7,
    icon: "mdi-shield-check-outline",
    link: "/masters/Role-and-Permissons",
    link2: "/masters/Role-and-Permisson/create-role-and-permission",
    permissions: ["r_roles"],
  },
  {
    title: "Customization",
    number: 8,
    icon: "mdi-note-edit-outline",
    link: "/masters/customizations/item-groups",
    permissions: ["r_ms"],
  },
]

export const topMenuCustomizationTab = [
  {
    title: "Item Group",
    number: 9,
    icon: "mdi-account-circle-outline",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/item-groups",
    link2: "/masters/customizations/item-groups/create",
    permissions: ["r_ms"],
  },
  {
    title: "Item Sub Group",
    number: 10,
    icon: "mdi-domain",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/item-sub-groups",
    link2: "/masters/customizations/item-sub-groups/create",
    permissions: ["r_ms"],
  },
  {
    title: "Currency",
    number: 11,
    icon: "mdi-layers-outline",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/currencies",
    link2: "/masters/customizations/currencies/create",
    permissions: ["r_ms"],
  },
  {
    title: "VAT",
    number: 12,
    icon: "mdi-book-account-outline",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/vats",
    link2: "/masters/customizations/vats/create",
    permissions: ["r_ms"],
  },
  {
    title: "Payment Term",
    number: 13,
    icon: "mdi-treasure-chest-outline",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/payment-terms",
    link2: "/masters/customizations/payment-terms/create",
    permissions: ["r_ms"],
  },
  {
    title: "Payment Method",
    number: 14,
    icon: "mdi-bookshelf",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/payment-methods",
    link2: "/masters/customizations/payment-methods/create",
    permissions: ["r_ms"],
  },
  {
    title: "Shipping Term",
    number: 15,
    icon: "mdi-warehouse",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/shipping-terms",
    link2: "/masters/customizations/shipping-terms/create",
    permissions: ["r_ms"],
  },
  {
    title: "Shipping Method",
    number: 16,
    icon: "mdi-shield-check-outline",
    parent_link: "/masters/customizations",
    link: "/masters/customizations/shipping-methods",
    link2: "/masters/customizations/shipping-methods/create",
    permissions: ["r_ms"],
  },
]